tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                    '#0b1326',
        'surface-dim':                '#0b1326',
        'surface-bright':             '#31394d',
        'surface-container-lowest':   '#060e20',
        'surface-container-low':      '#131b2e',
        'surface-container':          '#171f33',
        'surface-container-high':     '#222a3d',
        'surface-container-highest':  '#2d3449',
        'on-surface':                 '#dae2fd',
        'on-surface-variant':         '#bcc9c6',
        'inverse-surface':            '#dae2fd',
        'inverse-on-surface':         '#283044',
        'outline':                    '#879391',
        'outline-variant':            '#3d4947',
        'surface-tint':               '#6bd8cb',
        'primary':                    '#6bd8cb',
        'on-primary':                 '#003732',
        'primary-container':          '#29a195',
        'on-primary-container':       '#00302b',
        'inverse-primary':            '#006a61',
        'primary-fixed':              '#89f5e7',
        'primary-fixed-dim':          '#6bd8cb',
        'on-primary-fixed':           '#00201d',
        'on-primary-fixed-variant':   '#005049',
        'secondary':                  '#ffb690',
        'on-secondary':               '#552100',
        'secondary-container':        '#ec6a06',
        'on-secondary-container':     '#4a1c00',
        'secondary-fixed':            '#ffdbca',
        'secondary-fixed-dim':        '#ffb690',
        'on-secondary-fixed':         '#341100',
        'on-secondary-fixed-variant': '#783200',
        'tertiary':                   '#4edea3',
        'on-tertiary':                '#003824',
        'tertiary-container':         '#00a572',
        'on-tertiary-container':      '#00311f',
        'tertiary-fixed':             '#6ffbbe',
        'tertiary-fixed-dim':         '#4edea3',
        'on-tertiary-fixed':          '#002113',
        'on-tertiary-fixed-variant':  '#005236',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
        'background':                 '#0b1326',
        'on-background':              '#dae2fd',
        'surface-variant':            '#2d3449',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        xs:     '4px',
        sm:     '12px',
        base:   '8px',
        md:     '24px',
        lg:     '40px',
        xl:     '64px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        'data-md':     ['JetBrains Mono', 'monospace'],
        'data-lg':     ['JetBrains Mono', 'monospace'],
        'label-caps':  ['JetBrains Mono', 'monospace'],
        'body-md':     ['Inter', 'sans-serif'],
        'body-lg':     ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'data-md':     ['14px', { lineHeight: '20px',  fontWeight: '500' }],
        'data-lg':     ['18px', { lineHeight: '24px',  fontWeight: '500' }],
        'label-caps':  ['12px', { lineHeight: '16px',  fontWeight: '700', letterSpacing: '0.05em' }],
        'body-md':     ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'body-lg':     ['18px', { lineHeight: '28px',  fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px',  fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px',  fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-xl': ['48px', { lineHeight: '56px',  fontWeight: '700', letterSpacing: '-0.02em' }],
      },
    },
  },
}
